# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Darko Automate

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mysqlclient
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up Chromedriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
        CHROMEDRIVER_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
        CHROMEDRIVER_VERSION="${CHROMEDRIVER_VERSION}.0.0.0"
    
        CHROMEDRIVER_DIR="./chromedriver"
        mkdir $CHROMEDRIVER_DIR
    
        # Download and install Chromedriver
        wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR
    
        # Print Chromedriver version and path
        chromedriver --version
        echo "Chromedriver path: $CHROMEDRIVER_DIR"
    - name: Execute script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
      run: |
          python app.py
