# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Darko Automate

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        CHROME_VERSION="google-chrome-stable_116.0.5845.187-1_amd64.deb"
        wget https://dl.google.com/linux/direct/$CHROME_VERSION
        sudo dpkg -i $CHROME_VERSION
        sudo apt-get install -f
        rm $CHROME_VERSION
        pip install mysqlclient
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
      run: |
          python app.py
